module "TESTE_MODULE" {
  source = "../modules-aws/"
  codcliente = ""
  env = ""
  iniciaiscliente = ""
  envnumber = ""
  instance_type_linux = "t2.micro"
  instance_type_windows = "t2.micro"
  key_name = ""
  tag_shutdown = ""
  tag_startup = ""
  AWS_ACCESS = ""
  AWS_SECRET = ""
  AWS_REGION = "sa-east-1"
  Nome_VPC = "Mv Clientes"
  dns_name = "cloudmv.com.br."
  cidr1a = "10.2.0.0/26"
  cidr1b = "10.2.0.64/26"
  cidr1c = "10.2.0.128/26"
}
